### PR TITLE
Working PMF: This One First

### LINKED ISSUE #91: PMF Outputs a constant value

### PR DESCRIPTION
**Pull request by orionw**
Closes #91

### CODE REVIEW

**Comment by bjschoenfeld** [comment]
tests do not pass

**Comment by orionw** [comment]
What tests?  I don't modify any metrics or model that are tested?

**Comment by bjschoenfeld** [comment]
```
......EE.
======================================================================
ERROR: test_dag_lstm_regression_determinism (test_models.ModelDeterminismTestCase)
----------------------------------------------------------------------
...
TypeError: _get_data_loader() missing 2 required positional arguments: 'batch_size' and 'drop_last'

======================================================================
ERROR: test_dna_regression_determinism (test_models.ModelDeterminismTestCase)
----------------------------------------------------------------------
...
TypeError: _get_data_loader() missing 2 required positional arguments: 'batch_size' and 'drop_last'
```

**Comment by orionw** [comment]
Should be fixed now.

**Comment by bjschoenfeld** [comment]
please fix merge conflicts

**Comment by orionw** [comment]
Merge conflicts are resolved

**Comment by orionw** [comment]
Since both PR's would need the refactor and the next one branches off of this one, I am closing this PR and doing it in the next PR

**Pull request closed without merging**
