### PR TITLE
Add timing

### LINKED ISSUE #3: Time Train and Test Phases
Know the predict time of this meta-model will allow us to compare the merits of using such a model vs running the actual pipeline.

### PR DESCRIPTION
**Pull request by orionw**
- separate branch BTW
- Adds model times for train/test on regression/rank/fit
- Outputs to terminal and file

Closes #3

### CODE REVIEW

**Comment by bjschoenfeld** [comment]
This is a great start. Let's create a timer context manager as described [here](https://preshing.com/20110924/timing-your-code-using-pythons-with-statement/) and let's use the `time.perf_counter` to measure start and end timestamps because it is made for timing code performance.

**Comment by orionw** [comment]
I would disagree.  Those timers don’t use actual clock time - they use the measurement of the CPU clock which may or may not align with real time (https://stackoverflow.com/questions/25785243/understanding-time-perf-counter-and-time-process-time).  So we could perhaps more accurately measure the comparison using those (aka see a more precise difference) but it would have no real time value that anyone could relate to.  Plus I think time.time() can be good to +- 2 ms which is pretty close.  We don’t need more accuracy than that.

**Comment by orionw** [comment]
As to the link you shared, if you'd like to create a class to manage that instead of calling time.time() and then taking the difference, we could.  It seems a little cleaner to make a class, but we are only calling time.time() 6 times.  So I think if we were comparing lines of code, it's probably more to make a class (although it might be more readable).

**Comment by bjschoenfeld** [comment]
Ok. `time.time` does make more sense. Good find.

The context manager is not that important.

**Pull request merged**
