### PR TITLE
Random model

### PR DESCRIPTION
**Pull request by orionw**
- Random rank model implementation

### CODE REVIEW

**Comment by bjschoenfeld** [comment]
Please branch of develop when making new features. This has the linear regression model in it, so I cannot merge it until the linear regression model branch is merged in.

**Comment by orionw** [comment]
Yes, I did that on purpose.  I usually include a note but didn't on this one.

**Comment by bjschoenfeld** [comment]
> Yes, I did that on purpose. I usually include a note but didn't on this one.

That's fine if there is a purpose. Why did you see it as necessary? Looking at it casually, I don't see that it was necessary.

**Comment by orionw** [comment]
Yeah this one would probably be fine, I just like to know that I don't create two conflicting PR's.  This allows me to be sure that both PR's work together and I don't run into any surprises.

**Comment by bjschoenfeld** [comment]
Looking at this PR vs #38, there are differences in the the linear regression model. It looks like you added the ranking element here. This means there will be merge conflicts. It would be better to have the linear regression model changes all contained in that one PR.

**Comment by orionw** [comment]
If you merge in the Linear Regression model, there will be no merge conflicts.  The git history will see essentially the same as one branch.  After all, I had the changes in #38 before I made these ones.

**Comment by bjschoenfeld** [comment]
You are probably right, there will be no conflicts.

**Pull request merged**
