### PR TITLE
Removed pearson computation from the rank problem

### PR DESCRIPTION
**Pull request by erikhuck**

### CODE REVIEW

**Comment by orionw** [comment]
Why are we talking out Pearson computation? It's similar to the Spearman one, but no the same?

**Comment by bjschoenfeld** [comment]
As @orionw pointed out to me, Pearson of ranked values is Spearman. So, it seems like having Pearson in the rank problem is redundant. Pearson should still be a part of the regression problem.

Also, we were passing predicted ranks and true F1 scores to Pearson. This is weird to find the correlation between rank and true regression targets (not true rank targets).

Does this sound good?

**Comment by orionw** [comment]
Yeah that makes sense.  It'll make our table lopsided, but even if we made it true rank vs predicted rank and did Pearson it should be same as Spearman (though maybe we should keep both and check that).

However, if we want a full table of metrics, maybe we should just keep it.  Always easy to take code out later and it's not hurting anything.

**Comment by bjschoenfeld** [comment]
> It'll make our table lopsided

I am thinking we will need a table per task type.

> if we made it true rank vs predicted rank and did Pearson it should be same as Spearman (though maybe we should keep both and check that)

This could be checked when we do our metrics tests.

> Always easy to take code out later and it's not hurting anything.

It is currently not correct, so something has to change.

**Comment by orionw** [comment]
Yeah a table per task type could work.   I guess we have the autosklearn regression hole unless we fill that in with k-n-pipelines also.  

I would say the code *is* correct, it's just redundant.  It is correctly getting a pearson coefficient between the values.  I feel like we should leave this code in until the metric tests are in - it could help be a sanity check on our tests and debugging or prove to us there is a difference in edge cases.  There's a lot more code in the `scipy.spearmanr` than the 2 lines I sent you.  I'd hate to take out this code and then end up putting it back in because we determined there is a difference.  

Aka, let's first verify that it's redundant and then remove it.  Currently we're hypothesizing.  And like I said, if it's not hurting anything and not incorrect, let's not remove it until we're sure.

**Comment by bjschoenfeld** [comment]
> I would say the code is correct, it's just redundant.

No, for the reason I stated above:

> Also, we were passing predicted ranks and true F1 scores to Pearson. This is weird to find the correlation between rank and true regression targets (not true rank targets).

If we wanted to find the Pearson correlation between predicted ranks (values between 0 and n-1) and the true F1 score (values between 0 and 1), then yes we are computing that correctly.

**Comment by orionw** [comment]
Again I would disagree.  It is a correct spearman of the two ranks.

The two lines I sent you over slack:
```
# Gets the ranks and rank differences
x_ranked = rankdata(x, axis=0)
rs = ma.corrcoef(x_ranked, rowvar=False).data
``` 
These rank the data (and do other things before that I didn't look at) before it goes into the correlation coefficient function.  So they're both turned into ranks for the speamanr function.  It's definitely a correct spearman values for the predicted ranks and true ranks. 

Now whether that will be equal to the Pearson version is yet to be seen.  Maybe?  I didn't look into the function more than what I sent you, but there were a lot of if statements for different conditions.  I was just saying lets leave it until we actually look into it and can make an informed decision / go through the testing process.

**Comment by bjschoenfeld** [comment]
> It is a correct spearman of the two ranks.

It is not spearman, it is pearson. This is the key line being removed:

`coefficient, p_value = pearson_correlation(pd.DataFrame(predicted_ranks)['rank'], pd.DataFrame(actual_ranks)['test_f1_macro'])`

**Comment by orionw** [comment]
Oh my bad.  Let's talk about this in person.  My other work has some pressing deadlines and I think I'm getting confused.

**Pull request merged**
