### PR TITLE
Update Badge 

### PR DESCRIPTION
**Pull request by orionw**
Badge was showing unknown, this fixes it.

### CODE REVIEW

**Comment by bjschoenfeld** [comment]
If you want to do this, can you make badges for master and develop, like this: https://github.com/byu-dml/metalearn/pull/199/files

**Comment by orionw** [comment]
I mean, the master one isn't working because it doesn't have a codecov / travis file but sure.

**Comment by bjschoenfeld** [comment]
It will, when dev gets merged into master. :)

**Comment by orionw** [comment]
Sure. It's done.

**Pull request merged**
